WITH DateCTE AS (
    SELECT CAST('2025-01-01' AS DATE) AS CalendarDate
    UNION ALL
    SELECT DATEADD(DAY, 1, CalendarDate)
    FROM DateCTE
    WHERE CalendarDate < '2025-01-31'
)
SELECT * FROM DateCTE
OPTION (MAXRECURSION 1000);
